### ISSUE TITLE
ro'yxat elementidan foydalanganingiz yaxshi

### ISSUE THREAD

**Issue by AbdunazarovU** [WnnR23/myteam#1]
Odatda `nav` ichidagi linklar ro'yxat elementi sifatida beriladi.

https://github.com/WnnR23/myteam/blob/c33c1276c18d4497cd20b42a4aacdeade0f4856a/index.html#L28-L29

**Comment by WnnR23** [comment]
Ro'yhat elementi ishlatildi!
